---
#========================================
#   Global Settings
#========================================
global_settings:
  controller:
    hostname: asgard-apic01.rich.ciscolabs.com
    type: apic
    username: admin
    version: 6.0(4c)
  management_epgs:
    - name: inband
      type: inb
    - name: ooband
      type: oob
