---
system_settings:
  apic_connectivity_preference:
    interface_to_use_for_external_connections: ooband
  bgp_route_reflector:
    autonomous_system_number: 65065
    route_reflector_nodes:
      pods:
      - pod_id: 1
        nodes: [101, 102]
