---
#========================================
#   Global Settings
#========================================
global_settings:
  controller:
    domain: RICH
    hostname: odin-nd01.rich.ciscolabs.com
    type: ndo
    username: tyscott
    version: 4.2(2e)
  management_epgs:
    - name: inband
      type: inb
    - name: ooband
      type: oob
